stages:
  - Build
  - Test
  - Deploy
  
before_script:
    - pip install --user JPype1
    - pip install --user pyinstaller


build:
  stage: Build
  tags:
    - shell
  script:
    - cd lib/openrocketjava/
    - ant clean
    - ant jar
  artifacts:
    paths:
      - lib/build/jar/OpenRocket.jar
    expire_in: 1 week
    
package:
  stage: Build
  tags:
    - shell
  script:
    - cd src/
    - pyinstaller monte_carlo.spec


unittest-java:
  stage: Test
  tags:
    - shell
  script:
    - cd lib/openrocketjava/
    - ant unittest
  allow_failure: false

test-python-args:
    stage: Test
    tags:
      - shell
    script:
      - cd src/
      - cp ../lib/build/jar/OpenRocket.jar ../lib/build/jar/openrocket.jar
      - pytest test_args.py

test-python-listeners:
    stage: Test
    tags:
      - shell
    script:
      - cd src/
      - cp ../lib/build/jar/OpenRocket.jar ../lib/build/jar/openrocket.jar
      - pytest test_sim_listeners.py


deploy:
  stage: Deploy
  tags:
    - shell
  script:
    - echo "deploy"
    - exit 0
  allow_failure: true
