stages:
  - Build
  - Test
  - Deploy
  - Package
  
before_script:
    - pip install --user JPype1
    - pip install --user pyinstaller


build:
  stage: Build
  tags:
    - shell
  script:
    - cd lib/openrocketjava/
    - ant clean
    - ant jar
  artifacts:
    paths:
      - lib/build/jar/OpenRocket.jar
    expire_in: 1 week
    
package:
  stage: Package
  tags:
    - shell
  script:
    - cd src/
    - python -m PyInstaller monte_carlo.spec


unittest-java:
  stage: Test
  tags:
    - shell
  script:
    - cd lib/openrocketjava/
    - ant unittest
  allow_failure: false

test-python-args:
    stage: Test
    tags:
      - shell
    script:
      - cd src/
      - cp ../lib/build/jar/OpenRocket.jar ../lib/build/jar/openrocket.jar
      - python -m pytest test_args.py

test-python-listeners:
    stage: Test
    tags:
      - shell
    script:
      - cd src/
      - cp ../lib/build/jar/OpenRocket.jar ../lib/build/jar/openrocket.jar
      - python -m pytest test_args.py
    artifacts:
      when: on_failure
      paths:
        - src/*.log
      expire_in: 1 day

test-output-file:
    stage: Test
    tags:
      - shell
    script:
      - cd src/
      - cp ../lib/build/jar/OpenRocket.jar ../lib/build/jar/openrocket.jar
      - python -m pytest test_results.py
    artifacts:
      when: on_failure
      paths:
        - src/*.log
      expire_in: 1 day

# test-gui:
#     stage: Test
#     tags:
#       - shell
#     script:
#       - cd src/
#       - cp ../lib/build/jar/OpenRocket.jar ../lib/build/jar/openrocket.jar
#       - python -m pytest test_gui.py
#     artifacts:
#       when: on_failure
#       paths:
#         - src/*.log
#       expire_in: 1 day

deploy:
  stage: Deploy
  tags:
    - shell
  script:
    - echo "deploy"
    - exit 0
  allow_failure: true
