stages:
  - Build
  - Test
  - Package
  
before_script:
    - pip install --user JPype1
    - pip install --user pyinstaller
    - pip install -r requirements.txt


build:
  stage: Build
  tags:
    - shell
  script:
    - cd lib/openrocketjava/
    - ant clean
    - ant jar
  artifacts:
    paths:
      - lib/build/jar/OpenRocket.jar
    expire_in: 2 days
    
package:
  stage: Package
  tags:
    - shell
  script:
    - cd src/
    - python -m PyInstaller monte_carlo.spec


unittest-java:
  stage: Test
  tags:
    - shell
  script:
    - cd lib/openrocketjava/
    - ant unittest
  allow_failure: false

test-python-args:
    stage: Test
    tags:
      - shell
    script:
      - cd src/
      - cp ../lib/build/jar/OpenRocket.jar ../lib/build/jar/openrocket.jar
      - python -m pytest test_args.py

test-python-output-file:
    stage: Test
    tags:
      - shell
    script:
      - cd src/
      - cp ../lib/build/jar/OpenRocket.jar ../lib/build/jar/openrocket.jar
      - python -m pytest test_results.py
    artifacts:
      when: on_failure
      paths:
        - src/*.log
      expire_in: 1 day

test-python-results-average:
    stage: Test
    tags:
      - shell
    script:
      - cd src/
      - cp ../lib/build/jar/OpenRocket.jar ../lib/build/jar/openrocket.jar
      - python -m pytest test_results_average.py
    artifacts:
      when: on_failure
      paths:
        - src/*.log
      expire_in: 1 day

test-python-upwind-rocket-vectors:
    stage: Test
    tags:
      - shell
    script:
      - cd src/
      - cp ../lib/build/jar/OpenRocket.jar ../lib/build/jar/openrocket.jar
      - python -m pytest test_upwind_rocket_vectors.py
    artifacts:
      when: on_failure
      paths:
        - src/*.log
      expire_in: 1 day